from bangazon.api.serializers.serializer_customer import CustomerSerializer, AdminCustomerSerializer
from bangazon.api.serializers.serializer_product import ProductSerializer
from bangazon.api.serializers.serializer_product_type import ProductTypeSerializer
from bangazon.api.serializers.serializer_order import OrderSerializer
from bangazon.api.serializers.serializer_training_program import TrainingProgramSerializer
from bangazon.api.serializers.serializer_payment_type import PaymentTypeSerializer
from bangazon.api.serializers.serializer_department import DepartmentSerializer
from bangazon.api.serializers.serializer_computer import ComputerSerializer
from bangazon.api.serializers.serializer_employee import EmployeeSerializer
from bangazon.api.serializers.serializer_customer_support_ticket import CustomerSupportTicketSerializer
